# render.yaml
services:
  - type: web
    name: sistema-escolar
    env: python
    startCommand: "gunicorn wsgi:app"
    buildCommand: "pip install -r requirements.txt"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    databaseId: sistema-escolar-db

databases:
  - name: sistema-escolar-db
    databaseName: sistema_escolar
    user: sistema_escolar_user
    ipAllowList: []